### PR TITLE
cathub module for database interface

### PR DESCRIPTION
**Pull request by kirstenwinther**

### CODE REVIEW

**Comment by mhoffman** [comment]
What is the minimum test coverage for CatKit? Having tests on this should be beneficial. Just wondering what would be the best test setup? Should we create another test database in the .travis.yml?

**Comment by jboes** [comment]
I'm not strictly imposing a minimum test coverage on my own modules yet, but I do agree that this is important for internal and external users. I will put some effort into that as soon as I get a documentation page up and running. 

Currently, the travis.yaml file searches for a tests directory in each submodule, so please do add testing at your leisure.

**Comment by mhoffman** [comment]
I like the module naming: catkit.(flow/gen/hub).

Re: the coverage. I was wondering about this since the coverage/coveralls tests say they are failing (see above) what we have to do to fix them. And ideally, fix it in a way that it is easy to add meaningful tests for the CLI scripts in the future.

**Comment by jboes** [comment]
The latest version runs nosetest in the ./catkit root directory which recursively looks for py files in all folders with an __init__.py file or in directories named test/tests. It's more convenient for handling basic import testing (it will automatically run the imports in each py file to see if the packages are available in the test build).

I think coveralls is currently set to fail at any reduction of coverage. I'm not sure how to set a minimum, but I think 80% is a reasonable goal for all modules.

**Comment by mhoffman** [comment]
Agreed, so the preliminary target would be to get test coverage back to ~58%?

**Comment by jboes** [comment]
That would be great

**Pull request merged**
